language: java
sudo: true

before_install:
  - sudo apt-get update -yq
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install msttcorefonts -qq

jdk:
- oraclejdk7
- openjdk6
- openjdk7

script:
- ./gradlew --no-color build

after_failure: sh print-examples-test-output.sh
