language: java

sudo: true

services:
- docker

jdk:
- oraclejdk7
- openjdk7
- oraclejdk8

before_install:
# We have to change the hostname to work around a bug in openjdk7 that crashes when the hostname is
# too long.
- export OLD_HOSTNAME=`hostname` && sudo sed -i -e "s/$OLD_HOSTNAME/test/g" /etc/hosts && sudo hostname test

# Don't run eval ./gradlew assemble"
install: []

script:
- ./gradlew --no-color build

after_failure:
- cat core/build/reports/checkstyleReports/main.xml
- cat core/build/reports/findbugsReports/main.xml
- cat core/build/reports/tests/index.html
- sh travis/print-examples-test-output.sh

deploy:
- provider: script
  script: travis/publish.sh
  skip_cleanup: true
  on:
    repo: mapfish/mapfish-print
    java: oraclejdk7
